// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: address.proto

package usdtpayment

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AddressService_BatchImport_FullMethodName  = "/proto.AddressService/BatchImport"
	AddressService_ToggleStatus_FullMethodName = "/proto.AddressService/ToggleStatus"
)

// AddressServiceClient is the client API for AddressService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AddressServiceClient interface {
	BatchImport(ctx context.Context, in *BatchImportRequest, opts ...grpc.CallOption) (*BatchImportResponse, error)
	ToggleStatus(ctx context.Context, in *ToggleStatusRequest, opts ...grpc.CallOption) (*ToggleStatusResponse, error)
}

type addressServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAddressServiceClient(cc grpc.ClientConnInterface) AddressServiceClient {
	return &addressServiceClient{cc}
}

func (c *addressServiceClient) BatchImport(ctx context.Context, in *BatchImportRequest, opts ...grpc.CallOption) (*BatchImportResponse, error) {
	out := new(BatchImportResponse)
	err := c.cc.Invoke(ctx, AddressService_BatchImport_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressServiceClient) ToggleStatus(ctx context.Context, in *ToggleStatusRequest, opts ...grpc.CallOption) (*ToggleStatusResponse, error) {
	out := new(ToggleStatusResponse)
	err := c.cc.Invoke(ctx, AddressService_ToggleStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddressServiceServer is the server API for AddressService service.
// All implementations must embed UnimplementedAddressServiceServer
// for forward compatibility
type AddressServiceServer interface {
	BatchImport(context.Context, *BatchImportRequest) (*BatchImportResponse, error)
	ToggleStatus(context.Context, *ToggleStatusRequest) (*ToggleStatusResponse, error)
	mustEmbedUnimplementedAddressServiceServer()
}

// UnimplementedAddressServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAddressServiceServer struct {
}

func (UnimplementedAddressServiceServer) BatchImport(context.Context, *BatchImportRequest) (*BatchImportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchImport not implemented")
}
func (UnimplementedAddressServiceServer) ToggleStatus(context.Context, *ToggleStatusRequest) (*ToggleStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ToggleStatus not implemented")
}
func (UnimplementedAddressServiceServer) mustEmbedUnimplementedAddressServiceServer() {}

// UnsafeAddressServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AddressServiceServer will
// result in compilation errors.
type UnsafeAddressServiceServer interface {
	mustEmbedUnimplementedAddressServiceServer()
}

func RegisterAddressServiceServer(s grpc.ServiceRegistrar, srv AddressServiceServer) {
	s.RegisterService(&AddressService_ServiceDesc, srv)
}

func _AddressService_BatchImport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchImportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressServiceServer).BatchImport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AddressService_BatchImport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressServiceServer).BatchImport(ctx, req.(*BatchImportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressService_ToggleStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressServiceServer).ToggleStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AddressService_ToggleStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressServiceServer).ToggleStatus(ctx, req.(*ToggleStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AddressService_ServiceDesc is the grpc.ServiceDesc for AddressService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AddressService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AddressService",
	HandlerType: (*AddressServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BatchImport",
			Handler:    _AddressService_BatchImport_Handler,
		},
		{
			MethodName: "ToggleStatus",
			Handler:    _AddressService_ToggleStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "address.proto",
}
