# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
      
    - name: Install Protoc
      uses: arduino/setup-protoc@v2
      with:
        version: "25.x"

    - name: Build
      run: make build-proto

    - name: Commit files
      run: |
        git config --local user.email "gitrobot@clearcode.cn"
        git config --local user.name "gitrobot"
        git add . 
        git commit -a -m "build proto files"
        git tag -a -m "build proto files" v0.$(date +%Y%M%d%H%M%S)

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        force: true
        tags: true

    - name: WeChat Work notification by text
      run: |
        content="### <font color=\"info\">构建成功</font> \n> 地址: https://github.com/user/repository/actions/runs/${{ github.run_id }}"
        curl https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=693axxx6-7aoc-4bc4-97a0-0ec2sifa5aaa \
        -H 'Content-Type: application/json' \
        -d "{\"msgtype\": \"markdown\",\"markdown\": {\"content\": \"${content}\"}}"
      env:
        WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}